# Skip the command line flags and use a gadget.toml configuration file.
# Either pass the config location as a command or just execute gadget from the same directory.
# Flags specified in the command will override values set in the configuration file.

# The name of the binary.
# app_name = "gadget_binary"

# The address to run the app on. If none is specified, Gadget will try to find an available port on localhost to use.
# app_address = "localhost:8090"

# The path to the project to build, if no value is set, Gadget will use the current directory.
# app_path = "/path/to/project"

# Arguments to pass to go when building the binary.
# build_args = ["-gcflags=all=-N -l"]

# The port to connect debugger. If not set, Gadget will find an available port.
# listen_port = 3811

# The host to connect debugger. If not set, will default to 127.0.0.1
# listen_host = 127.0.0.1

# Directories that shouldn't trigger rebuild. Hidden directories are automatically excluded from watching.
# exclude_dirs = []

# Files that shouldn't trigger rebuild. The generated binary is automatically excluded, no need to include it. Hidden files
#   are not automatically excluded. Add them here.
# exclude_files = [".gitignore", "README.md"]

# Files with these extensions won't trigger rebuild.
# exclude_exts = []

# Files beginning with a sequence of chars matching these won't trigger rebuild.
# exclude_prefix = []

# Directories that should prompt rebuild. Useful for specifying custom paths to other modules in use by a project.
# include_dirs = []

# Files that should prompt rebuild.
# include_files = []
